name: ğŸ”— æ£€æŸ¥é“¾æ¥

on:
  workflow_dispatch:
  schedule:
    - cron: "00 16 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: generate links.md
        env:
          key: ${{ secrets.key }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
        run: |
          go run generate_md.go
          cat Links.md

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: >-
            --verbose
            --no-progress
            'Links.md'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: ğŸ”— é“¾æ¥æ£€æŸ¥æŠ¥å‘Š
          content-filepath: ./lychee/out.md
          labels: report
